# Generated by Django 3.2 on 2021-05-02 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('nome', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Dottore',
                'verbose_name_plural': 'Dottori',
                'db_table': 'docs_doctor',
            },
        ),
        migrations.CreateModel(
            name='Paycheck',
            fields=[
                ('basicdoc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='docs.basicdoc')),
                ('totale', models.FloatField()),
                ('trattenute', models.FloatField()),
                ('TRF', models.FloatField()),
                ('giorni', models.IntegerField()),
                ('bonus_renzi', models.FloatField()),
            ],
            options={
                'verbose_name': 'Busta paga',
                'verbose_name_plural': 'Buste paga',
                'db_table': 'docs_paycheck',
            },
            bases=('docs.basicdoc',),
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('nome', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Specializzazione',
                'verbose_name_plural': 'Specializzazioni',
                'db_table': 'docs_speciality',
            },
        ),
        migrations.CreateModel(
            name='MedicalDoc',
            fields=[
                ('basicdoc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='docs.basicdoc')),
                ('spesa', models.FloatField(blank=True, null=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.doctor')),
            ],
            options={
                'verbose_name': 'Documento medico',
                'verbose_name_plural': 'Documenti medici',
                'db_table': 'docs_medical_doc',
            },
            bases=('docs.basicdoc',),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specializzazione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.speciality'),
        ),
    ]
